services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AawTeam\BackendRoles\:
    resource: '../Classes/*'

  cache.backend_roles:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['backend_roles']

  AawTeam\BackendRoles\Role\Definition\Loader:
    arguments:
      $cache: '@cache.backend_roles'

  AawTeam\BackendRoles\Command\SynchronizeCommand:
    arguments:
      $locker: '@locker.backend_roles_synchronization'
    tags:
      - name: 'console.command'
        command: 'backendroles:synchronize'
        schedulable: false

  AawTeam\BackendRoles\FormEngine\BackendRoleSelectItemsProcessor:
    public: true

  AawTeam\BackendRoles\Imaging\IconHandler:
    public: true

  locker.backend_roles_synchronization:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Locking\LockFactory', 'createLocker']
    arguments: ['backend_roles_synchronization']
