name: ci-main
run-name: CI for branch main
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '1.0'
      - '1.1'
      - '2.0'
      - '2.1'
  pull_request:
    branches-ignore:
      - '1.0'
      - '1.1'
      - '2.0'
      - '2.1'
jobs:
  integrity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint PHP
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} lint:php
      - name: Composer validate
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} composer:validate
  composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer update
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} composer:install
  cgl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer update
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} composer:install
      - name: Composer normalize
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} -n composer:normalize
      - name: CGL check
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} -n test:qa:cgl
      - name: PHPStan
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} test:qa:phpstan
      - name: Rector
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} -n test:qa:rector
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer update
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} composer:install
      - name: Unit testing
        run: Build/Scripts/builder.sh -p ${{ matrix.php }} test:unit
